---
- name: Install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: true

- name: Ensure PostgreSQL is started and enabled
  service:
    name: postgresql
    state: started
    enabled: true

- name: Allow PostgreSQL inbound from workload zone only
  community.general.ufw:
    rule: allow
    to_port: "5432"
    proto: tcp
    from_ip: "{{ workload_cidr }}"
    direction: in
