---
- name: Register all hosts in Checkmk
  hosts: all
  become: false
  gather_facts: true

  vars:
    checkmk_url:  "{{ lookup('env', 'CHECKMK_SERVER_URL') }}/cmk/check_mk"
    checkmk_pass: "{{ lookup('env', 'CHECKMK_ADMIN_PASS') }}"
    domain:       "{{ lookup('env', 'LIGHT_DOMAIN') }}"

  tasks:
    - name: Add host to Checkmk
      uri:
        url: "{{ checkmk_url }}/api/1.0/domain-types/host_config/collections/all"
        method: POST
        user: cmkadmin
        password: "{{ checkmk_pass }}"
        force_basic_auth: true
        validate_certs: false
        body_format: json
        body:
          host_name: "{{ inventory_hostname }}.{{ domain }}"
          folder: "/"
          attributes:
            ipaddress: "{{ ansible_host }}"
        status_code: [200, 201, 422]
        timeout: 30

    - name: Activate Checkmk changes
      uri:
        url: "{{ checkmk_url }}/api/1.0/domain-types/activation_run/actions/activate-changes/invoke"
        method: POST
        user: cmkadmin
        password: "{{ checkmk_pass }}"
        force_basic_auth: true
        validate_certs: false
        body_format: json
        body:
          redirect: false
        status_code: [200, 202]
        timeout: 30
      run_once: true
