---
- name: Register all hosts in Foreman
  hosts: all
  become: false
  gather_facts: true

  vars:
    foreman_url: "https://{{ lookup('env', 'IP_FOREMAN') }}"
    foreman_user: "{{ lookup('env', 'FOREMAN_ADMIN_USER') }}"
    foreman_pass: "{{ lookup('env', 'FOREMAN_ADMIN_PASS') }}"

  tasks:
    - name: Ensure host exists in Foreman
      theforeman.foreman.host:
        server_url: "{{ foreman_url }}"
        username: "{{ foreman_user }}"
        password: "{{ foreman_pass }}"
        validate_certs: false
        name: "{{ inventory_hostname }}"
        ip: "{{ ansible_default_ipv4.address }}"
        environment: "production"
        state: present
