#!/usr/bin/env python3
"""
Generate Docker Compose, DNS zone additions, and Ansible group_vars
from config/topology.json.

Outputs:
  environments/dev/docker/docker-compose.topology.yml
  environments/dev/docker/config/dns/zones/db.topology
  ansible/group_vars/bubble_<name>.yml   (one per bubble)

Usage:
  python3 scripts/lib/gen_topology.py <topology.json> <light_root> <env> <location> <domain> <config.env>
"""

import json
import sys
import os
from pathlib import Path


# ── Load environment config values ────────────────────────────────────────────

def load_env(env_path):
    vals = {}
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            vals[k.strip()] = v.strip().strip('"').strip("'")
    return vals


# ── YAML helpers (no PyYAML dependency) ───────────────────────────────────────

def _indent(text, n):
    pad = " " * n
    return "\n".join(pad + l if l else l for l in text.splitlines())

def _str(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    return str(v)

def _yaml_val(v, indent=0):
    if isinstance(v, dict):
        if not v:
            return "{}"
        lines = []
        for k, val in v.items():
            rendered = _yaml_val(val, indent + 2)
            if isinstance(val, (dict, list)) and val:
                lines.append(f"{' '*indent}{k}:")
                lines.append(rendered)
            else:
                lines.append(f"{' '*indent}{k}: {rendered}")
        return "\n".join(lines)
    elif isinstance(v, list):
        if not v:
            return "[]"
        lines = []
        for item in v:
            rendered = _yaml_val(item, indent + 2)
            if isinstance(item, (dict, list)):
                first_line = rendered.lstrip()
                lines.append(f"{' '*indent}- {first_line}")
                # remaining lines already indented
            else:
                lines.append(f"{' '*indent}- {rendered}")
        return "\n".join(lines)
    elif isinstance(v, str):
        if any(c in v for c in ':{}&*!,|>\'"%@`') or v == "" or v in ("true","false","null"):
            return f'"{v}"'
        return v
    else:
        return _str(v)


# ── Docker Compose generation ─────────────────────────────────────────────────

def gen_compose(topology, env, location, domain, cfg):
    ip_puppet  = cfg.get("IP_PUPPET",      "10.10.0.21")
    ip_checkmk = cfg.get("IP_CHECKMK",     "10.10.0.23")
    ip_pulp    = cfg.get("IP_PULP",        "10.10.0.24")
    ip_dns     = cfg.get("IP_DNS_PRIMARY", "10.10.0.30")

    lines = [
        "# Auto-generated by scripts/lib/gen_topology.py — do not edit manually.",
        "# Source of truth: config/topology.json",
        "",
        "networks:",
    ]

    bubbles = {k: v for k, v in topology["bubbles"].items() if not k.startswith("_")}

    # Network definitions
    for bname, bubble in bubbles.items():
        cidr = bubble["cidr"]
        lines += [
            f"  bubble-{bname}:",
            f"    driver: bridge",
            f"    ipam:",
            f"      config:",
            f"        - subnet: \"{cidr}\"",
        ]

    lines += ["", "services:"]

    # Extend management services to bridge into each bubble
    # Fixed offsets within each bubble: .2=ansible, .3=checkmk, .10=jumphost
    lines += ["", "  ansible:"]
    lines += ["    networks:"]
    for bname, bubble in bubbles.items():
        base = ".".join(bubble["cidr"].split(".")[:3])
        lines += [f"      bubble-{bname}:", f"        ipv4_address: \"{base}.2\""]

    lines += ["", "  checkmk:"]
    lines += ["    networks:"]
    for bname, bubble in bubbles.items():
        base = ".".join(bubble["cidr"].split(".")[:3])
        lines += [f"      bubble-{bname}:", f"        ipv4_address: \"{base}.3\""]

    lines += ["", "  jumphost:"]
    lines += ["    networks:"]
    for bname, bubble in bubbles.items():
        base = ".".join(bubble["cidr"].split(".")[:3])
        lines += [f"      bubble-{bname}:", f"        ipv4_address: \"{base}.10\""]

    # Bubble member containers
    for bname, bubble in bubbles.items():
        lines += [f"", f"  # ── Bubble: {bname} ({bubble['cidr']}) {'─'*40}"]
        for member in bubble["members"]:
            mname      = member["name"]
            func       = member["function"]
            ip         = member["ip"]
            svc_key    = f"{bname}-{mname}"
            container  = f"{env}-{location}-srv-{bname}-{mname}"
            hostname   = f"{container}.{domain}"

            expose_ports = []
            # Map container port to a unique host port: 10.{bubble_idx}.{port}
            # Simple rule: host port = 40000 + hash(svc_key) % 20000
            for expose in member.get("expose", []):
                port = expose["port"]
                # deterministic local port: use bubble index * 1000 + port
                bidx = list(bubbles.keys()).index(bname)
                host_port = 40000 + bidx * 1000 + port % 1000
                expose_ports.append(f"127.0.0.1:{host_port}:{port}")

            lines += [
                f"",
                f"  {svc_key}:",
                f"    build:",
                f"      context: ./build/workload",
                f"      dockerfile: Dockerfile",
                f"    container_name: \"{container}\"",
                f"    hostname: \"{hostname}\"",
                f"    networks:",
                f"      bubble-{bname}:",
                f"        ipv4_address: \"{ip}\"",
                f"    environment:",
                f"      PUPPET_SERVER: \"{ip_puppet}\"",
                f"      CHECKMK_SERVER: \"{ip_checkmk}\"",
                f"      PULP_SERVER: \"{ip_pulp}\"",
                f'    dns: ["{ip_dns}"]',
                f"    restart: unless-stopped",
                f"    healthcheck:",
                f"      test: [\"CMD\", \"nc\", \"-z\", \"localhost\", \"22\"]",
                f"      interval: 30s",
                f"      timeout: 5s",
                f"      retries: 3",
                f"      start_period: 30s",
            ]
            if expose_ports:
                lines += ["    ports:"]
                for p in expose_ports:
                    lines += [f"      - \"{p}\""]

    return "\n".join(lines) + "\n"


# ── DNS zone additions ────────────────────────────────────────────────────────

def gen_dns(topology, env, location, domain):
    lines = [
        f"; topology bubble hosts — auto-generated from config/topology.json",
        f"; Included by named.conf — do not edit manually.",
        "",
    ]
    bubbles = {k: v for k, v in topology["bubbles"].items() if not k.startswith("_")}
    for bname, bubble in bubbles.items():
        lines.append(f"; Bubble: {bname}")
        for member in bubble["members"]:
            hostname = f"{env}-{location}-srv-{bname}-{member['name']}"
            lines.append(f"{hostname}  IN  A  {member['ip']}")
        lines.append("")
    return "\n".join(lines)


# ── Ansible group_vars per bubble ─────────────────────────────────────────────

def gen_group_vars(bname, bubble, env, location, domain, cfg):
    base = ".".join(bubble["cidr"].split(".")[:3])
    members = bubble["members"]

    lines = [
        f"---",
        f"# Auto-generated from config/topology.json — do not edit manually.",
        f"",
        f"bubble_name: \"{bname}\"",
        f"bubble_cidr: \"{bubble['cidr']}\"",
        f"",
        f"bubble_members:",
    ]
    for m in members:
        container = f"{env}-{location}-srv-{bname}-{m['name']}"
        lines.append(f"  - name: \"{container}\"")
        lines.append(f"    ip: \"{m['ip']}\"")
        lines.append(f"    role: \"{m.get('role', '')}\"")

    lines += ["", "# Per-member IP shortcuts for role variables"]
    for m in members:
        var_name = f"{bname}_{m['name']}_ip".replace("-", "_")
        lines.append(f"{var_name}: \"{m['ip']}\"")

    lines += [
        "",
        f"# Management zone IPs (inherited from config/light.env)",
        f"mgmt_zone_cidr: \"{cfg.get('MGMT_ZONE_CIDR', '10.10.0.0/24')}\"",
        f"puppet_server:  \"{cfg.get('IP_PUPPET', '10.10.0.21')}\"",
        f"checkmk_server: \"{cfg.get('IP_CHECKMK', '10.10.0.23')}\"",
        f"pulp_server:    \"{cfg.get('IP_PULP', '10.10.0.24')}\"",
        f"jumphost_ip:    \"{cfg.get('IP_JUMPHOST', '10.10.0.10')}\"",
        f"ansible_server: \"{cfg.get('IP_ANSIBLE', '10.10.0.22')}\"",
        f"dns_servers:",
        f"  - \"{cfg.get('IP_DNS_PRIMARY', '10.10.0.30')}\"",
        f"  - \"{cfg.get('IP_DNS_SECONDARY', '10.10.0.31')}\"",
        f"ntp_servers:",
        f"  - \"{cfg.get('IP_NTP_PRIMARY', '10.10.0.32')}\"",
        f"  - \"{cfg.get('IP_NTP_SECONDARY', '10.10.0.33')}\"",
    ]
    return "\n".join(lines) + "\n"


# ── Vagrantfile for hybrid mode (Docker mgmt zone + Vagrant workload VMs) ────

def gen_vagrantfile(topology, env, location, domain, cfg):
    """One VirtualBox VM per bubble member; provisioned with route to mgmt zone."""
    bubbles  = {k: v for k, v in topology["bubbles"].items() if not k.startswith("_")}
    ip_puppet = cfg.get("IP_PUPPET",      "10.10.0.21")
    ip_dns    = cfg.get("IP_DNS_PRIMARY", "10.10.0.30")
    mgmt_cidr = cfg.get("MGMT_ZONE_CIDR", "10.10.0.0/24")

    lines = [
        "# Auto-generated by scripts/lib/gen_topology.py — do not edit manually.",
        "# Source of truth: config/topology.json",
        "# Used by: environments/dev/startup.sh when LIGHT_RUNTIME=hybrid",
        "",
        'Vagrant.configure("2") do |config|',
        '  config.vm.box = "bento/ubuntu-22.04"',
        '  config.vm.provider "virtualbox"',
        "  config.ssh.insert_key = false",
        "",
    ]

    for bname, bubble in bubbles.items():
        cidr    = bubble["cidr"]
        base    = ".".join(cidr.split(".")[:3])
        host_gw = f"{base}.1"   # VirtualBox host-only gateway (.1 is the host)

        lines.append(f'  # ── Bubble: {bname} ({cidr}) {"─" * 42}')
        lines.append("")

        for member in bubble["members"]:
            mname     = member["name"]
            ip        = member["ip"]
            container = f"{env}-{location}-srv-{bname}-{mname}"
            fqdn      = f"{container}.{domain}"

            lines += [
                f'  config.vm.define "{container}" do |node|',
                f'    node.vm.hostname = "{fqdn}"',
                f'    node.vm.network "private_network", ip: "{ip}"',
                f'    node.vm.provider "virtualbox" do |vb|',
                f'      vb.name   = "{container}"',
                f'      vb.memory = 1024',
                f'      vb.cpus   = 1',
                f'    end',
                f'    node.vm.provision "shell", inline: <<-SHELL',
                f'      set -e',
                f'      # Route management zone through VirtualBox host-only gateway',
                f'      ip route add {mgmt_cidr} via {host_gw} 2>/dev/null || true',
                f'      grep -qxF "ip route add {mgmt_cidr} via {host_gw}" /etc/rc.local 2>/dev/null \\',
                f'        || printf "\\nip route add {mgmt_cidr} via {host_gw} 2>/dev/null || true\\n" >> /etc/rc.local',
                f'      chmod +x /etc/rc.local',
                f'      # Point DNS at management zone server',
                f'      printf "nameserver {ip_dns}\\n" > /etc/resolv.conf',
                f'      # Install puppet-agent (internet bootstrap; Pulp used for subsequent packages)',
                f'      if ! command -v puppet >/dev/null 2>&1; then',
                f'        wget -q https://apt.puppet.com/puppet7-release-jammy.deb -O /tmp/puppet.deb',
                f'        dpkg -i /tmp/puppet.deb && apt-get update -qq',
                f'        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq puppet-agent',
                f'      fi',
                f'      mkdir -p /etc/puppetlabs/puppet',
                f'      printf "[main]\\nserver = {ip_puppet}\\nenvironment = production\\nruninterval = 1800\\n" \\',
                f'        > /etc/puppetlabs/puppet/puppet.conf',
                f'    SHELL',
                f'  end',
                f'',
            ]

    lines.append("end")
    return "\n".join(lines) + "\n"


# ── Main ──────────────────────────────────────────────────────────────────────

# ── Static Ansible inventory ──────────────────────────────────────────────────
# Used in dev before Foreman is fully populated.
# Foreman dynamic inventory takes over once hosts are registered.

def gen_inventory(topology, env, location, domain, cfg):
    bubbles = {k: v for k, v in topology["bubbles"].items() if not k.startswith("_")}
    lines = [
        "# Auto-generated from config/topology.json — do not edit manually.",
        "# This static inventory is used during initial deployment.",
        "# After registration, ansible/inventory/foreman.yml is the live source.",
        "",
        "[all:vars]",
        f"ansible_user=admin",
        f"ansible_ssh_common_args='-o StrictHostKeyChecking=no'",
        "",
    ]

    for bname, bubble in bubbles.items():
        lines += [f"[bubble_{bname}]"]
        for m in bubble["members"]:
            container = f"{env}-{location}-srv-{bname}-{m['name']}"
            lines.append(f"{container} ansible_host={m['ip']}")
        lines.append("")

    # All bubble members in one group for baseline playbook
    lines += ["[bubble_all:children]"]
    for bname in bubbles:
        lines.append(f"bubble_{bname}")
    lines.append("")

    # Function groups (function_web, function_db, etc.) across all bubbles
    func_groups: dict = {}
    for bname, bubble in bubbles.items():
        for m in bubble["members"]:
            func = m["function"]
            container = f"{env}-{location}-srv-{bname}-{m['name']}"
            func_groups.setdefault(func, []).append(container)

    for func, hosts in func_groups.items():
        lines += [f"[function_{func}]"]
        lines += hosts
        lines.append("")

    return "\n".join(lines)


# ── Bubble summary (printed to stdout for startup.sh) ─────────────────────────

def gen_bubble_list(topology, env, location, domain):
    """Return list of (bubble_name, [(container_name, ip, role), ...])"""
    bubbles = {k: v for k, v in topology["bubbles"].items() if not k.startswith("_")}
    result = []
    for bname, bubble in bubbles.items():
        members = []
        for m in bubble["members"]:
            container = f"{env}-{location}-srv-{bname}-{m['name']}"
            members.append((container, m["ip"], m.get("role", "")))
        result.append((bname, members))
    return result


def main():
    if len(sys.argv) < 7:
        print("Usage: gen_topology.py <topology.json> <light_root> <env> <location> <domain> <light.env>")
        sys.exit(1)

    topology_path, light_root, env, location, domain, env_path = sys.argv[1:7]
    root = Path(light_root)

    with open(topology_path) as f:
        topology = json.load(f)

    cfg = load_env(env_path) if Path(env_path).exists() else {}

    # Docker Compose overlay
    compose_out = root / "environments/dev/docker/docker-compose.topology.yml"
    compose_out.write_text(gen_compose(topology, env, location, domain, cfg))
    print(f"  wrote {compose_out}")

    # DNS zone additions (included by db.simple-test.org via $INCLUDE)
    dns_out = root / "environments/dev/docker/config/dns/zones/db.topology"
    dns_out.write_text(gen_dns(topology, env, location, domain))
    print(f"  wrote {dns_out}")

    # Ansible group_vars per bubble
    gvars_dir = root / "ansible/group_vars"
    gvars_dir.mkdir(exist_ok=True)
    bubbles = {k: v for k, v in topology["bubbles"].items() if not k.startswith("_")}
    for bname, bubble in bubbles.items():
        out = gvars_dir / f"bubble_{bname}.yml"
        out.write_text(gen_group_vars(bname, bubble, env, location, domain, cfg))
        print(f"  wrote {out}")

    # Static inventory (used during initial deploy, before Foreman is populated)
    inv_out = root / "ansible/inventory/topology.ini"
    inv_out.write_text(gen_inventory(topology, env, location, domain, cfg))
    print(f"  wrote {inv_out}")

    # Vagrantfile for hybrid mode (Docker mgmt zone + Vagrant workload VMs)
    vagrant_dir = root / "environments/dev/vagrant"
    vagrant_dir.mkdir(exist_ok=True)
    vagrant_out = vagrant_dir / "Vagrantfile.topology"
    vagrant_out.write_text(gen_vagrantfile(topology, env, location, domain, cfg))
    print(f"  wrote {vagrant_out}")

    # Machine-readable bubble list for startup.sh
    for bname, members in gen_bubble_list(topology, env, location, domain):
        for container, ip, role in members:
            print(f"  MEMBER:{bname}:{container}:{ip}:{role}")


if __name__ == "__main__":
    main()
