#!/usr/bin/env bash
# Generate config/light.env with sane defaults and random secrets.
# Called by: ./startup.sh --init

set -euo pipefail

LIGHT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${LIGHT_ROOT}/lib/logging.sh"

ENV_FILE="${LIGHT_ROOT}/config/light.env"

# ── Guard: don't silently clobber an existing config ──────────────────────────
if [[ -f "${ENV_FILE}" ]]; then
    log::warn "config/light.env already exists."
    printf "Overwrite? [y/N] "
    read -r answer
    [[ "${answer}" =~ ^[Yy]$ ]] || { log::info "Aborted — existing config kept."; exit 0; }
fi

# ── Secret generation ─────────────────────────────────────────────────────────
# Produces a 24-character alphanumeric string.
# openssl rand gives enough bytes that tr -dc always has plenty to work with.
gen_secret() {
    openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 24
}

FOREMAN_PASS="$(gen_secret)"
CHECKMK_PASS="$(gen_secret)"
PULP_PASS="$(gen_secret)"

# ── Write config/light.env ────────────────────────────────────────────────────
# Variables expanded here (passwords, home dir detection for SSH key hint):
#   ${FOREMAN_PASS}, ${CHECKMK_PASS}, ${PULP_PASS}
# Variables kept literal in the file (escaped with \):
#   \${IP_PUPPET}, \${LIGHT_DOMAIN} — so the file stays self-referential

cat > "${ENV_FILE}" <<EOF
# light configuration — generated by ./startup.sh --init on $(date -u '+%Y-%m-%d %H:%M UTC')
# Edit any value and re-run ./startup.sh dev

# ── Domain ────────────────────────────────────────────────────────────────────
LIGHT_DOMAIN="localhost"

# ── Environment ───────────────────────────────────────────────────────────────
LIGHT_ENV="dev"
LIGHT_PROVIDER="local"
LIGHT_RUNTIME="hybrid"          # hybrid (default) | docker | vagrant

# ── Naming (hostname: {env}-{location}-{type}-{function}-{seq}.{LIGHT_DOMAIN})
LIGHT_LOCATION="local"

# ── Network ───────────────────────────────────────────────────────────────────
MGMT_ZONE_CIDR="10.10.0.0/24"
MGMT_GATEWAY="10.10.0.1"       # Docker mgmt-zone bridge IP (hybrid mode router)

# ── Management zone service IPs ───────────────────────────────────────────────
IP_JUMPHOST="10.10.0.10"
IP_FOREMAN="10.10.0.20"
IP_PUPPET="10.10.0.21"
IP_ANSIBLE="10.10.0.22"
IP_CHECKMK="10.10.0.23"
IP_PULP="10.10.0.24"
IP_DNS_PRIMARY="10.10.0.30"
IP_DNS_SECONDARY="10.10.0.31"
IP_NTP_PRIMARY="10.10.0.32"
IP_NTP_SECONDARY="10.10.0.33"

# ── Credentials (auto-generated — store these somewhere safe) ─────────────────
ADMIN_SSH_KEY_PATH="\${HOME}/.ssh/id_ed25519.pub"
ADMIN_SSH_KEY_PRIVATE="\${HOME}/.ssh/id_ed25519"
FOREMAN_ADMIN_USER="admin"
FOREMAN_ADMIN_PASS="${FOREMAN_PASS}"
CHECKMK_ADMIN_PASS="${CHECKMK_PASS}"
PUPPET_CA_SERVER="\${IP_PUPPET}"
PULP_ADMIN_PASS="${PULP_PASS}"

# ── Cloud provider credentials (fill only the provider you use) ───────────────
LINODE_TOKEN=""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_REGION="eu-central-1"
GCP_PROJECT=""
GCP_REGION="europe-west3"
GOOGLE_APPLICATION_CREDENTIALS=""

# ── Pulp mirror ───────────────────────────────────────────────────────────────
PULP_SYNC_UBUNTU="true"
PULP_SYNC_DEBIAN="true"
PULP_SYNC_RHEL="false"

# ── Monitoring alerts ─────────────────────────────────────────────────────────
ALERT_EMAIL="linux-admins@\${LIGHT_DOMAIN}"
EOF

# ── SSH key check ─────────────────────────────────────────────────────────────
SSH_KEY="${HOME}/.ssh/id_ed25519"
if [[ ! -f "${SSH_KEY}" ]]; then
    log::warn "SSH key not found: ${SSH_KEY}"
    log::warn "Generate one with: ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -C light-admin"
    log::warn "Then update ADMIN_SSH_KEY_PATH / ADMIN_SSH_KEY_PRIVATE in config/light.env"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
log::ok "Created config/light.env"
log::info ""
log::info "Generated secrets (save these):"
log::info "  Foreman:  ${FOREMAN_PASS}"
log::info "  Checkmk:  ${CHECKMK_PASS}"
log::info "  Pulp:     ${PULP_PASS}"
log::info ""
log::info "Domain: localhost  (edit LIGHT_DOMAIN to use your own)"
log::info ""
log::info "Next steps:"
log::info "  Review config/light.env"
log::info "  Edit config/topology.json to declare your service bubbles"
log::info "  Run: ./startup.sh dev"
